FROM tafilz/xamarin-android:33-latest

RUN apt-get update -oAcquire::AllowInsecureRepositories=true && \
    apt-get install -y --no-install-recommends --allow-unauthenticated \
        nuget \
        android-sdk-platform-tools \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
